plugins {
    id 'java-library'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'

    api 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation "org.apache.kafka:kafka-streams:3.6.1"

    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}